import { HabitCategory, HabitFrequency, TrackingType } from '@prisma/client';

// Tu usuario real
export const myUser = {
  id: 'rodrigo-gainz-factory',
  email: 'rodrigovdev01@gmail.com',
  password: '1Ewe9920.', // En producción, esto sería un hash real
  firstName: 'Rodrigo',
  lastName: 'Vásquez de Velasco',
  bio: 'Founder & CEO de Gainz Factory - Construyendo el futuro del desarrollo personal consciente',
  isActive: true,
};

// Tus hábitos reales organizados por categorías
export const myRealHabits = [
  // 🌅 RUTINA MATUTINA (Morning Routine)
  {
    name: 'Despertar temprano',
    description: 'Levantarse a las 6:00 AM para maximizar el día',
    category: HabitCategory.MORNING_ROUTINE,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.BINARY,
    points: 15,
    color: '#F59E0B',
    icon: '🌅',
    isActive: true,
    order: 1,
    userId: myUser.id,
  },
  {
    name: 'Presencia matutina',
    description: 'Establecer la base de presencia plena - el fundamento de la verdadera inteligencia',
    category: HabitCategory.MORNING_ROUTINE,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.DURATION,
    targetValue: 15,
    targetUnit: 'MINUTES',
    points: 30,
    color: '#8B5CF6',
    icon: '🧘‍♂️',
    isActive: true,
    order: 2,
    userId: myUser.id,
  },
  {
    name: 'Journaling matutino',
    description: 'Escribir pensamientos y intenciones del día',
    category: HabitCategory.MORNING_ROUTINE,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.DURATION,
    targetValue: 10,
    targetUnit: 'MINUTES',
    points: 15,
    color: '#6366F1',
    icon: '📔',
    isActive: true,
    order: 3,
    userId: myUser.id,
  },
  {
    name: 'Hidratación temprana',
    description: 'Beber 500ml de agua al despertar',
    category: HabitCategory.MORNING_ROUTINE,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.NUMERIC,
    targetValue: 500,
    targetUnit: 'ML',
    points: 10,
    color: '#06B6D4',
    icon: '💧',
    isActive: true,
    order: 4,
    userId: myUser.id,
  },

  // 💪 ENTRENAMIENTO FÍSICO (Physical Training)
  {
    name: 'Entrenamiento de fuerza',
    description: 'Sesión de pesas o ejercicios de resistencia',
    category: HabitCategory.PHYSICAL_TRAINING,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.DURATION,
    targetValue: 45,
    targetUnit: 'MINUTES',
    points: 35,
    color: '#DC2626',
    icon: '💪',
    isActive: true,
    order: 1,
    userId: myUser.id,
  },
  {
    name: 'Cardio',
    description: 'Actividad cardiovascular (correr, bicicleta, natación)',
    category: HabitCategory.PHYSICAL_TRAINING,
    frequency: HabitFrequency.WEEKLY,
    targetCount: 3,
    trackingType: TrackingType.DURATION,
    targetValue: 30,
    targetUnit: 'MINUTES',
    points: 25,
    color: '#F97316',
    icon: '🏃',
    isActive: true,
    order: 2,
    userId: myUser.id,
  },
  {
    name: 'Flexibilidad',
    description: 'Estiramientos y movilidad articular',
    category: HabitCategory.PHYSICAL_TRAINING,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.DURATION,
    targetValue: 15,
    targetUnit: 'MINUTES',
    points: 10,
    color: '#10B981',
    icon: '🧘',
    isActive: true,
    order: 3,
    userId: myUser.id,
  },

  // 🧠 DESARROLLO PERSONAL (Personal Development)
  {
    name: 'Lectura',
    description: 'Leer al menos 30 minutos de contenido educativo',
    category: HabitCategory.PERSONAL_DEVELOPMENT,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.DURATION,
    targetValue: 30,
    targetUnit: 'MINUTES',
    points: 20,
    color: '#3B82F6',
    icon: '📚',
    isActive: true,
    order: 1,
    userId: myUser.id,
  },
  {
    name: 'Meditación',
    description: 'Práctica de mindfulness y meditación',
    category: HabitCategory.PERSONAL_DEVELOPMENT,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.DURATION,
    targetValue: 20,
    targetUnit: 'MINUTES',
    points: 25,
    color: '#8B5CF6',
    icon: '🧘‍♀️',
    isActive: true,
    order: 2,
    userId: myUser.id,
  },
  {
    name: 'Planificación del día',
    description: 'Revisar y planificar las tareas del día siguiente',
    category: HabitCategory.PERSONAL_DEVELOPMENT,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.BINARY,
    points: 15,
    color: '#6366F1',
    icon: '📋',
    isActive: true,
    order: 3,
    userId: myUser.id,
  },

  // 🥗 NUTRICIÓN (Nutrition)
  {
    name: 'Comida saludable',
    description: 'Consumir al menos 3 comidas balanceadas al día',
    category: HabitCategory.NUTRITION,
    frequency: HabitFrequency.DAILY,
    targetCount: 3,
    trackingType: TrackingType.NUMERIC,
    points: 20,
    color: '#10B981',
    icon: '🥗',
    isActive: true,
    order: 1,
    userId: myUser.id,
  },
  {
    name: 'Hidratación',
    description: 'Beber al menos 2.5L de agua al día',
    category: HabitCategory.NUTRITION,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.NUMERIC,
    targetValue: 2500,
    targetUnit: 'ML',
    points: 15,
    color: '#06B6D4',
    icon: '💧',
    isActive: true,
    order: 2,
    userId: myUser.id,
  },
  {
    name: 'Suplementos',
    description: 'Tomar vitaminas y suplementos necesarios',
    category: HabitCategory.NUTRITION,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.BINARY,
    points: 10,
    color: '#F59E0B',
    icon: '💊',
    isActive: true,
    order: 3,
    userId: myUser.id,
  },

  // 😴 SUEÑO (Sleep)
  {
    name: 'Hora de dormir',
    description: 'Acostarse antes de las 11:00 PM',
    category: HabitCategory.SLEEP_RECOVERY,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.BINARY,
    points: 20,
    color: '#6366F1',
    icon: '😴',
    isActive: true,
    order: 1,
    userId: myUser.id,
  },
  {
    name: 'Calidad del sueño',
    description: 'Dormir al menos 7-8 horas de calidad',
    category: HabitCategory.SLEEP_RECOVERY,
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    trackingType: TrackingType.DURATION,
    targetValue: 480,
    targetUnit: 'MINUTES',
    points: 25,
    color: '#8B5CF6',
    icon: '🌙',
    isActive: true,
    order: 2,
    userId: myUser.id,
  },
];

// Tus challenges reales
export const myChallenges = [
  {
    name: 'Despertar temprano por 30 días',
    description: 'Levantarse a las 6:00 AM durante 30 días consecutivos',
    category: HabitCategory.MORNING_ROUTINE,
    startDate: new Date(),
    endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    targetValue: 30,
    currentValue: 0,
    isCompleted: false,
    reward: 'Ritual matutino establecido',
    userId: myUser.id,
  },
  {
    name: 'Entrenamiento de fuerza por 21 días',
    description: 'Completar 21 días consecutivos de entrenamiento de fuerza',
    category: HabitCategory.PHYSICAL_TRAINING,
    startDate: new Date(),
    endDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
    targetValue: 21,
    currentValue: 0,
    isCompleted: false,
    reward: 'Fuerza y resistencia mejoradas',
    userId: myUser.id,
  },
  {
    name: 'Lectura diaria por 60 días',
    description: 'Leer al menos 30 minutos diarios durante 60 días',
    category: HabitCategory.PERSONAL_DEVELOPMENT,
    startDate: new Date(),
    endDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    targetValue: 60,
    currentValue: 0,
    isCompleted: false,
    reward: 'Hábito de lectura consolidado',
    userId: myUser.id,
  },
];

// Función principal de seed simplificada
export async function seedDatabase() {
  console.log('Seed function temporarily disabled - use individual seed scripts instead');
  return;
} 